#spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mariadb://localhost:3306/db_thirds?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.security.user.name=pablo
spring.security.user.password=1234
#spring.jpa.properties.hibernate.format_sql=true

# Keycloak configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://contables.unicauca.edu.co:80/auth/realms/oauth2-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://contables.unicauca.edu.co:80/auth/realms/oauth2-realm/protocol/openid-connect/certs

logging.level.org.Keycloak=DEBUG

jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resource-id=microservices_client

server.port=8081
