spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MariaDBDialect
spring.security.user.name=${SECURITY_USER}
spring.security.user.password=${SECURITY_PASSWORD}
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Keycloak configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://contables.unicauca.edu.co:80/auth/realms/oauth2-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://contables.unicauca.edu.co:80/auth/realms/oauth2-realm/protocol/openid-connect/certs

logging.level.org.Keycloak=DEBUG
jwt.auth.converter.principle-attribute=preferred_username
jwt.auth.converter.resource-id=microservices_client